### ISSUE TITLE
Listen all events from the gateway

### ISSUE THREAD

**Issue by EugeneYarem19** [openwebnet/rx-openwebnet#10]
Hello)
Thank you for this great library)
I want to listen to all messages from the gateway. Unfortunately, I can see that `public Observable<List<OpenSession>> listen(OpenMessage... requests)` hasn't been implemented yet. Will you implement this method in near time?
If don't, could you tell me, how can I implement this opportunity (listen to all messages from the gateway)?

**Comment by niqdev** [comment]
Hello @EugeneYarem19 , sorry for the late answer!

Correct, [this](https://github.com/openwebnet/rx-openwebnet/blob/master/lib/src/main/java/com/github/niqdev/openwebnet/OpenWebNet.java#L65) method is not implemented and unfortunately I do not have time to make any progress on this at the moment. So any help is more than welcome.

As far as I know it should be enough to send a `Channel.EVENT` frame to start receiving notifications, but honestly I never investigate it too much.
If you want to implement it I would recommend to look at the official [documentation](https://www.myopen-legrandgroup.com/) first and then try to connect manually using `netcat` for example and see what are the frames that you receive back and if they are reliable. Also if you can filter them somehow, to don't get overflowed.
After that you might be able to reuse some of the utility methods that are already there to parse the frames.

Let me know if you need more help and thanks again for your interest in this project!

**Comment by EugeneYarem19** [comment]
@niqdev , I have an idea how it can be implemented. I'm going to try it on Saturday. I'll write to you on the next week)

**Comment by niqdev** [comment]
Awesome, thanks!

**Comment by EugeneYarem19** [comment]
So...
I've tried to listen the gateway via react-native-tcp (I'm a React Native Developer) and it work's. This question is closed for me now. Sorry, I won't be able to help you with implementing of this feature in your library in near time. But I can say that you have almost all parameters and functions to implement it) Good luck)

**Comment by niqdev** [comment]
Thanks for your feedback!
